locales:
  wyr:
    name: Wayoró Keyboards
    description: >-
      Mobile OS keyboards for the Wayoró language from the Divvun group
      at UiT.
  en:
    name: Wayoró Keyboards
    description: >-
      Mobile OS keyboards for the Wayoró language from the Divvun group
      at UiT.
  nb:
    name: Wayoró tastatur
    description: Mobiltastatur for Wayoró fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
